cross_prediction in place of correct_prediction.
NameError: global name 'correct_prediction' is not defined so it needs cross_prediction in place of correct_prediction.